### ISSUE TITLE
Pull request and proposed changes

### ISSUE THREAD

**Issue by sveggiani** [Pagebakers/soapsource#5]
Hi @Pagebakers ! I've made a pull request with some changes to the repo. Could you take a look?

Besides, what do you think about to modify the passed parameters management by not requiring to pass them encapsulated in another array?

Thanks!

**Comment by dvlprs** [comment]
Hi everyone, just got this error: 

> Strict (2048): Declaration of SoapSource::listSources() should be compatible with DataSource::listSources($data = NULL) [APP/Model/Datasource/SoapSource.php, line 30]

Fixed by changing line #152 to:

    public function listSources($data = NULL) {

Hope this helps

**Comment by Pagebakers** [comment]
Oh man, sorry I didn't respond. My github notifications were turned off for a long time without knowing.

@sveggiani I merged your PR.

@dvlprs Feel free to make a PR for that.
